name: cy_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.11
  webrtc_interface: ^1.2.0
  provider: ^6.1.2       
  http: 1.3.0           
  shared_preferences: ^2.5.2 
  video_player: ^2.9.3
  socket_io_client: 3.0.2
  firebase_core: 3.12.1
  firebase_auth: 5.5.1
  cloud_firestore: 5.6.5
  google_sign_in: 6.2.2
  flutter_facebook_auth: ^7.1.1
  flutter_spinkit: ^5.2.1
  web_socket_channel: 3.0.2
  html: ^0.15.0
  url_launcher: 6.3.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/signup_video.mp4
  - assets/google.png
  - assets/facebook.png
  - assets/twitter.png
  - assets/icons/n11.png
  - assets/icons/amazon.jpg
  - assets/icons/trendyol.png
  - assets/icons/carr.jpg
  - assets/icons/shopping_cart.png
  - assets/icons/vaccine.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700